INSERT INTO manufacturer (manufacturer_name, country, photo_link, description_short, more_description,) VALUES 
('ANANTA', 'BGD', "https://images.squarespace-cdn.com/content/v1/56f8db55b09f95c715703572/1473146121435-QAUIZYJV23PJ2MPMWNP0/ke17ZwdGBToddI8pDm48kOcNHCJyjcrFlNyrZxgcoWwUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcMX35BGZ7pL0UjrUpAfzSUB4tWMBE1_mQAR8Xu39-geGqHt5sm0MQ3CW3MPlJd4nI/DSC06095.JPG?format=1500w", "Established in 1992.has an annual turnover exceeding $300 million.", "Established in 1992, Ananta is engaged in the design, development and manufacturing of private label apparel products for some of the leading brands and retailers in the world."),
("CK", "USA", "https://1.bp.blogspot.com/-1dcTaH2aDw8/U7g3g_h_SrI/AAAAAAAAB6M/B7kSME-208Q/s1600/garment+shop+floor_shahi.png", "The company was founded by designer Calvin Klein and his childhood friend, Barry K. Schwartz. The company is headquartered in Midtown Manhattan, New York City.", "Calvin Klein Inc. is an American fashion house established in 1968. It specializes in leather, lifestyle accessories, home furnishings, perfumery, jewellery, watches and ready-to-wear. The company has substantial market share in retail and commercial lines as well haute couture garments."),
("H&M", "SWE", "https://images.search.yahoo.com/search/images?p=production+line+of+h%26m+clothes+brand&fr=mcafee_uninternational&imgurl=https%3A%2F%2Fcdn.vox-cdn.com%2Fthumbor%2FyeTHi0jENvtyGsIR2M8dDYKsWKs%3D%2F0x0%3A5400x3600%2F1200x675%2Ffilters%3Afocal%282268x1368%3A3132x2232%29%2Fcdn.vox-cdn.com%2Fuploads%2Fchorus_image%2Fimage%2F58707751%2FH_M_BD_2014__81_.0.jpg#id=369&iurl=https%3A%2F%2Fimages.businessoffashion.com%2Fsite%2Fuploads%2F2016%2F06%2FNASSA_Group_AJ_Super_Garments_LTD_RMG_production_line.jpg%3Fcrop%3Dtop%26fit%3Dcrop%26h%3D576%26ixlib%3Dphp-1.1.0%26w%3D1024&action=click", "H&M is a Swedish global retail brand with a finger constantly on the pulse of fashion beating heart in order to source out trends and styles that even fashionable people with a budget can buy", "It is a good thing that H&M is a brand consumers can trust because they offer fabulous fashion without the  exorbitant price tags.The collection range of the company covers all age groups and offers high-quality apparel and accessories for women, men, teenagers, and children.The origin of this Swedish brand goes back to the 1940s, according to the website of H&M. It was 1947 when Swedish entrepreneur Erling Persson opened a women clothing store in Sweden called Hennes, which actually meant Hers in English. Alright, so that is where H comes from"),
("Acropolis of Athens Apparel/ Ancient Greek Gifts", "GRC", "https://libcom.org/files/images/history/textile%20worker.jpg", " Greece has long experience in the clothing industry, ever since ancient times", "The traditions and usage of high-quality Greek cotton have made apparel production in Greece some of the highest quality in Europe. All experts have experience with new machinery and work with all fabrics. While people prefer to produce in cheaper locations in Europe, the quality of the work and knowledge really shine in Greece");


INSERT INTO orders (order_date, cloth_id, quantity, customer_code) VALUES 
('2020-02-20', 7, 1,'wns0001234'),
('2020-05-20', 6, 3,'wns0001244'),
('2020-08-20', 5, 5,'wns0001254'),
('2020-11-20', 4, 3,'wns0001264'),
('2021-02-21', 3, 2,'wns0001274');

INSERT INTO clothes (code, manufacturer_id, image_filename, short_description, description_more, promo) VALUES
('cotn71301', 1, 'images/trousers_black.png', 'best cotton products.designed to fit all age variants, to look elegant and feels natural','best cotton products.designed to fit all age variants, to look elegant and feels natural', FALSE),
('cotn71401', 6,'images/trousers_blue.png','best cotton products.designed to fit all age variants, to look elegant and feels natural','best cotton products.designed to fit all age variants, to look elegant and feels natural.best cotton products.designed to fit all age variants, to look elegant and feels natural', TRUE),
('P21MTBk', 3,'images/trousers_black.png', '100% Polyester', 'Adjustable waist cord for comfort', TRUE),
('PC21TG', 5,'image/trouser_gray', '90% Polyester, 10% Spandex', '(Swanky Appearance)Athletic fit Tapered Gym Joggers with skin friendly surface, Regular thighs and snug fit legs without friction and irritation. Tips:They are Slim Fit Design, One size up when you prefer loose fit.', FALSE),
('P21JB ', 2, 'image/jacket_dblue.png', '100% polyester', 'FUNCTIONALITY: Center front zipper closure: Two welt pockets with zipper closures; Flight pocket on left sleeve with zipper closure.', TRUE),
('B08FDCL5ZR ', 4,'image/T-Shirt_grey.png ', '90% Cotton, 10% Polyester', 'If you are into archaeological sites and history of the ancient world, then this awesome Athens acropolis gift is just for you -- or any fan of Greek mythology, Greek vacations, and Greek history.', TRUE),
('B08G2F1JMQ ', 6, 'image/women-T-Shirt_green.png ', '100% Cotton,Greece Hellas Greek National Flag Heritage Gift', 'Perfect Summer Vacation, Travel Outfit for any Fan of Greece. This Flag Map of Hellas & Greek makes a perfect Gift for any Greek citizen, Fan of the Greek Mythology & History. Greek Greece Hellas Outfit fur Greek Lovers and Summer Vacations & Travel Trips to Europe.', FALSE),
('cotn6717', 6, 'images/coat_brown.png', '100% cotton', 'can be dressed at all weather and geography', TRUE),
('B07NNN4HHQ', 7, 'image/Trouser_unisexnavy.png ', 'Machine wash cold with like colors, dry low heat', 'Solid colors: 80% Cotton, 20% Polyester; Heather Grey: 78% Cotton, 22% Poly; Dark Heather: 50% Cotton, 50% Polyester', TRUE);



